### ISSUE TITLE
Linking the executable IngestAndQuery is failing

### ISSUE THREAD

**Issue by satabdidas** [BitFunnel/BitFunnel#194] opened 2016-09-08 22:27 UTC
I am trying to build BitFunnel on the branch QueryParser and linking is failing because BitFunnel::StringToClassification is defined in two libraries -

```
Linking CXX executable IngestAndQuery
duplicate symbol __ZN9BitFunnel22StringToClassificationERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE in:
    ../../src/Common/Utilities/src/libUtilities.a(Stream.cpp.o)
    ../../src/Plan/src/libPlan.a(TermMatchNode.cpp.o)
```
Both the function and return values are defined in two places. And the enum literals with the same name have different values.

**Comment by danluu** [comment] 2016-09-08 23:47
I believe this is fixed by 4859cc42de81a5b4bdb9c29c0b1a0e2bf062aa21 but can't verify because I wasn't able to reproduce the failure. In general, we'd like to remove the concept of `Classification`, but I haven't removed it entirely -- I just removed the part that I thought was conflicting.

**Comment by danluu** [comment] 2016-09-09 00:22
Although I don't think it's technically necessary for this bug, I also removed the rest of the stuff in  bbe7e9a3b3e12c1b90e3562dbedada7c38bedd40 since it should be dead code.

**Comment by danluu** [comment] 2016-09-10 03:30
According to @satabdidas , this is fixed. Closing, although I find it disturbing that we see different results with the same compiler (although the OS version is different).

**Closed by danluu** 2016-09-10 03:30 UTC
